services:
  camera-ui:
    image: vitordm/camera.ui:latest
    container_name: camera-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "7272:7272"
      - "2727:2727"
      - "5050:5050"
    volumes:
      - /DATA/AppData/camera-ui:/data
    environment:
      TZ: America/Sao_Paulo

