name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker metadata
        id: metadata
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          echo "image=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_APPLICATION_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.metadata.outputs.image }}:${{ steps.metadata.outputs.sha_short }}
            ${{ steps.metadata.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
